# Generated by Django 6.0.6 on 2026-07-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
    ]
